spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e-commerce?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true